#!/bin/sh
#USAGE: mugsy-annotator allgenomes.fsa aln.maf *.gbk
#
#Features can be either a GFF3 file, a GBK genbank flat file, or 5 column text files ($featname $seqname $fmin $fmax $strand )
#Generate a multi-FASTA file with all your genome sequences
#cat genome1 ...genomeN > allgenomes.fsa

PREFIX=/usr/local/projects/angiuoli/mugsy_trunk/mapping

if [ ! -d "$PREFIX" ]
then
    echo "Cannot find installation directory $PREFIX. Edit the script to configure a valid directory"
    exit 1
fi

if [ $# -lt 3 ]
then
    echo "USAGE: mugsy-annotator allgenomes.fsa aln.maf *.gbk"
    exit 1
fi

IDXFILE=/tmp/$$.idx
FSAFILE=$1

echo "Building index for alignment $2" >&2
$PREFIX/mafindex.pl $IDXFILE < $2 > /tmp/$$.mafidx

shift
shift

for gff in $@
  do
  isgb=`head -1 $gff | grep "^LOCUS"`
  if [ "$isgb" != "" ]
      then
      echo "Converting file $gff to GFF" >&2
      `bp_genbank2gff3.pl --filter misc_feature -in stdin -out - < $gff | grep -v "# Input" >> /tmp/$$.gff`;
  else
      cat $gff >> /tmp/$$.gff
  fi
done
echo "Building index for features" >&2
$PREFIX/featureindex.pl $IDXFILE gff < /tmp/$$.gff > /tmp/$$.featidx
echo "Mapping features" >&2
echo "To print with aligment detail. Run $PREFIX/mapfeatures.pl --printalignments $IDXFILE $FSAFILE < /tmp/$$.gff" 
echo "To print with html reports. Run $PREFIX/mapfeatures.pl --printhtml $IDXFILE $FSAFILE < /tmp/$$.gff" 
$PREFIX/mapfeatures.pl $IDXFILE $FSAFILE < /tmp/$$.gff 

