#!/bin/sh
#USAGE: mugsymapper aln.maf features.txt allgenomes.fsa
#
#Features can be either a GFF3 file, a GBK genbank flat file, or 5 column text files ($featname $seqname $fmin $fmax $strand )
#Generate a multi-FASTA file with all your genome sequences
#cat genome1 ...genomeN > allgenomes.fsa

PREFIX=/usr/local/projects/angiuoli/developer/sangiuoli/mugsy/trunk/mapping

IDXFILE=/tmp/$$.idx

echo "Building index for alignment $1" >&2
$PREFIX/mafindex.pl $IDXFILE < $1 > /tmp/$$.mafidx
echo "Building index for features $2" >&2
$PREFIX/featureindex.pl $IDXFILE gff < $2 > /tmp/$$.featidx
echo "Mapping features" >&2
$PREFIX/mapfeatures.pl $IDXFILE $3 < $2 | grep -v "#"

